import { apiBaseUrl } from './env.js';

// [method, path, tag, summary, permission|null]
const OPS = [
  ['post', '/auth/login', 'Authentication', 'Sign in with email or username', null],
  ['post', '/auth/refresh', 'Authentication', 'Rotate the refresh-token cookie and get a new access token', null],
  ['post', '/auth/logout', 'Authentication', 'Sign out and revoke the session', null],
  ['get', '/auth/me', 'Authentication', 'Current user and permissions', 'any'],
  ['post', '/auth/change-password', 'Authentication', 'Change own password (revokes all sessions)', 'any'],
  ['get', '/auth/sessions', 'Authentication', 'List own active sessions', 'any'],
  ['delete', '/auth/sessions/{id}', 'Authentication', 'Revoke a session', 'any'],
  ['post', '/auth/sessions/revoke-others', 'Authentication', 'Revoke all other sessions', 'any'],
  ['get', '/users', 'Users', 'List the dashboard users', 'users:read'],
  ['post', '/users', 'Users', 'Create a user in a free role slot (max 3)', 'users:write'],
  ['patch', '/users/{id}', 'Users', 'Update a user', 'users:write'],
  ['post', '/users/{id}/reset-password', 'Users', 'Reset a user password', 'users:write'],
  ['post', '/users/{id}/unlock', 'Users', 'Unlock a locked account', 'users:write'],
  ['get', '/dashboard', 'Dashboard', 'Dashboard statistics, series and recent items', 'dashboard:read'],
  ['get', '/search', 'Search', 'Global search across modules', 'search:read'],
  ['get', '/activity', 'Activity', 'Global activity timeline', 'activity:read'],
  ['get', '/customers', 'Customers', 'List customers', 'customers:read'],
  ['post', '/customers', 'Customers', 'Create a customer', 'customers:write'],
  ['get', '/customers/{id}', 'Customers', 'Unified customer profile', 'customers:read'],
  ['patch', '/customers/{id}', 'Customers', 'Update a customer', 'customers:write'],
  ['post', '/customers/{id}/notes', 'Customers', 'Add a note', 'customers:write'],
  ['delete', '/customers/{id}/notes/{noteId}', 'Customers', 'Delete a note', 'customers:write'],
  ['post', '/customers/{id}/tags', 'Customers', 'Add tags', 'customers:write'],
  ['delete', '/customers/{id}/tags/{tag}', 'Customers', 'Remove a tag', 'customers:write'],
  ['get', '/whatsapp/conversations', 'WhatsApp', 'List conversations (inbox)', 'whatsapp:read'],
  ['get', '/whatsapp/conversations/{id}', 'WhatsApp', 'Get a conversation', 'whatsapp:read'],
  ['get', '/whatsapp/conversations/{id}/messages', 'WhatsApp', 'Conversation messages', 'whatsapp:read'],
  ['post', '/whatsapp/conversations/{id}/read', 'WhatsApp', 'Mark read', 'whatsapp:write'],
  ['post', '/whatsapp/conversations/{id}/unread', 'WhatsApp', 'Mark unread', 'whatsapp:write'],
  ['post', '/whatsapp/conversations/{id}/archive', 'WhatsApp', 'Archive', 'whatsapp:write'],
  ['patch', '/whatsapp/conversations/{id}', 'WhatsApp', 'Change status or priority', 'whatsapp:write'],
  ['post', '/whatsapp/conversations/{id}/assign', 'WhatsApp', 'Assign an operator', 'whatsapp:write'],
  ['post', '/whatsapp/conversations/{id}/tags', 'WhatsApp', 'Add a tag', 'whatsapp:write'],
  ['post', '/whatsapp/conversations/{id}/notes', 'WhatsApp', 'Add an internal note', 'whatsapp:write'],
  ['post', '/whatsapp/messages', 'WhatsApp', 'Send text, template or media message via MSG91', 'whatsapp:write'],
  ['get', '/whatsapp/templates', 'WhatsApp', 'List templates', 'whatsapp:read'],
  ['post', '/whatsapp/templates', 'WhatsApp', 'Register a template', 'whatsapp:write'],
  ['get', '/email', 'Email', 'Email history', 'email:read'],
  ['get', '/email/stats', 'Email', 'Email statistics', 'email:read'],
  ['post', '/email/send', 'Email', 'Send an email via Brevo', 'email:send'],
  ['get', '/email/{id}', 'Email', 'Email detail and events', 'email:read'],
  ['get', '/email/templates', 'Email', 'List templates', 'email:read'],
  ['post', '/email/templates', 'Email', 'Create a template', 'email:manage'],
  ['get', '/email/contacts', 'Email', 'Email contacts', 'email:read'],
  ['get', '/payments', 'Payments', 'List payments', 'payments:read'],
  ['get', '/payments/stats', 'Payments', 'Revenue and transaction statistics', 'payments:read'],
  ['get', '/payments/orders', 'Payments', 'List orders', 'payments:read'],
  ['get', '/payments/refunds', 'Payments', 'List refunds', 'payments:read'],
  ['post', '/payments/orders', 'Payments', 'Create a Razorpay order (amount in major units)', 'payments:write'],
  ['post', '/payments/verify', 'Payments', 'Verify checkout signature server-side', 'payments:write'],
  ['get', '/payments/{id}', 'Payments', 'Payment detail', 'payments:read'],
  ['post', '/payments/{id}/refund', 'Payments', 'Create a full or partial refund', 'payments:refund'],
  ['get', '/telegram/routes', 'Telegram', 'List routing rules', 'telegram:read'],
  ['post', '/telegram/routes', 'Telegram', 'Create a routing rule', 'telegram:write'],
  ['patch', '/telegram/routes/{id}', 'Telegram', 'Update a routing rule', 'telegram:write'],
  ['delete', '/telegram/routes/{id}', 'Telegram', 'Delete a routing rule', 'telegram:write'],
  ['post', '/telegram/routes/{id}/test', 'Telegram', 'Send a test message', 'telegram:write'],
  ['get', '/telegram/notifications', 'Telegram', 'Notification delivery log', 'telegram:read'],
  ['get', '/reports', 'Reports', 'Available reports', 'reports:read'],
  ['get', '/reports/{key}', 'Reports', 'Run a report', 'reports:read'],
  ['get', '/reports/{key}/csv', 'Reports', 'Download a report as CSV', 'reports:read'],
  ['get', '/integrations', 'Integrations', 'List integrations (secrets never returned)', 'integrations:read'],
  ['put', '/integrations/{provider}', 'Integrations', 'Save credentials (validated, encrypted at rest)', 'integrations:write'],
  ['post', '/integrations/{provider}/test', 'Integrations', 'Test connection', 'integrations:write'],
  ['post', '/integrations/{provider}/disconnect', 'Integrations', 'Disconnect', 'integrations:write'],
  ['get', '/integrations/types', 'Integrations', 'Integration types and the fields needed to add an account', 'integrations:read'],
  ['post', '/integrations/accounts', 'Integrations', 'Add another account of a type (tested before it is saved)', 'integrations:write'],
  ['patch', '/integrations/{provider}', 'Integrations', 'Rename an account or make it the default of its type', 'integrations:write'],
  ['delete', '/integrations/{provider}', 'Integrations', 'Remove an account added from the dashboard', 'integrations:write'],
  ['get', '/integrations/accounts/{type}', 'Integrations', 'Secret-free account list for pickers (visible to users of that feature)', null],
  ['get', '/webhooks', 'Webhooks', 'Webhook Center log', 'webhooks:read'],
  ['get', '/webhooks/{id}', 'Webhooks', 'Webhook event detail (redacted)', 'webhooks:read'],
  ['post', '/webhooks/{id}/retry', 'Webhooks', 'Retry a failed event', 'webhooks:retry'],
  ['post', '/webhooks/msg91', 'Webhooks', 'MSG91 receiver (shared-secret authenticated)', null],
  ['post', '/webhooks/brevo', 'Webhooks', 'Brevo account 1 receiver (bearer token authenticated)', null],
  ['post', '/webhooks/brevo2', 'Webhooks', 'Brevo account 2 receiver (bearer token authenticated)', null],
  ['post', '/webhooks/razorpay', 'Webhooks', 'Razorpay receiver (HMAC signature over raw body)', null],
  ['post', '/webhooks/{type}/{account}', 'Webhooks', 'Receiver for an account added from the dashboard (msg91 | brevo | razorpay), authenticated with that account\'s secret', null],
  ['get', '/settings', 'Settings', 'All settings sections', 'settings:read'],
  ['put', '/settings/{section}', 'Settings', 'Update a settings section', 'settings:write'],
  ['get', '/settings/notifications', 'Settings', 'Notification toggles', 'notifications:read'],
  ['put', '/settings/notifications', 'Settings', 'Update notification toggles', 'notifications:write'],
  ['get', '/health', 'Health', 'Public liveness probe', null],
  ['get', '/health/detailed', 'Health', 'Database, providers and system health', 'health:read'],
  ['post', '/health/probe', 'Health', 'Run the read-only provider checks now', 'health:read'],
  ['post', '/whatsapp/conversations/{id}/unarchive', 'WhatsApp', 'Unarchive', 'whatsapp:write'],
  ['delete', '/whatsapp/conversations/{id}/tags/{tag}', 'WhatsApp', 'Remove a tag', 'whatsapp:write'],
  ['patch', '/whatsapp/templates/{id}', 'WhatsApp', 'Update a template', 'whatsapp:write'],
  ['delete', '/whatsapp/templates/{id}', 'WhatsApp', 'Delete a template', 'whatsapp:write'],
  ['get', '/email/accounts', 'Email', 'List the Brevo sending accounts and whether each is configured', 'email:send'],
  ['get', '/email/templates/remote', 'Email', 'List templates stored in Brevo', 'email:manage'],
  ['patch', '/email/templates/{id}', 'Email', 'Update a template', 'email:manage'],
  ['delete', '/email/templates/{id}', 'Email', 'Delete a template', 'email:manage'],
  ['patch', '/email/contacts/{id}', 'Email', 'Update subscription / blocked state', 'email:manage'],
  ['get', '/telegram/bot', 'Telegram', 'Bot identity recorded at last verification', 'telegram:read'],
  ['get', '/telegram/discover', 'Telegram', 'Chats that recently messaged the bot (to find a chat ID)', 'telegram:write'],
  ['get', '/integrations/{provider}', 'Integrations', 'One integration (secret-free view)', 'integrations:read'],
  ['post', '/integrations/{provider}/connect', 'Integrations', 'Re-enable a disconnected integration', 'integrations:write'],
  ['get', '/webhooks/endpoints', 'Webhooks', 'Webhook URLs to register with each provider', 'webhooks:read'],
];

export function buildOpenApi() {
  const paths = {};
  for (const [method, path, tag, summary, perm] of OPS) {
    const params = [...path.matchAll(/\{(\w+)\}/g)].map((m) => ({ name: m[1], in: 'path', required: true, schema: { type: 'string' } }));
    (paths[`/api${path}`] ||= {})[method] = {
      tags: [tag], summary,
      description: perm && perm !== 'any' ? `Requires permission \`${perm}\`.` : undefined,
      security: perm ? [{ bearerAuth: [] }] : [],
      parameters: params,
      responses: {
        200: { description: 'Success: { success: true, message, data }' },
        401: { description: 'Unauthenticated' }, 403: { description: 'Forbidden' },
        400: { description: 'Validation error: { success:false, message, errorCode, data }' },
      },
    };
  }
  return {
    openapi: '3.0.3',
    info: { title: 'Unified Business Operations Dashboard API', version: '1.0.0', description: 'All responses use { success, message, data } / { success:false, message, errorCode, data:null }.' },
    servers: [{ url: apiBaseUrl() }],
    components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } },
    paths,
  };
}
